name: Tina

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.11.1
          - 4.10.1
          - 4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - run: opam pin add tina.dev --n .
      - name: Packages
        run: opam depext -yt tina
      - name: Dependecies
        run: opam install -t . --deps-only
      - name: Build
        run: opam exec -- dune build --profile release
      - name: Test
        run: opam exec -- dune runtest --profile release
